apiVersion: v1
kind: Service
metadata:
  name: nexus-backend
  namespace: nexus
  labels:
    app: nexus-backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: nexus-backend
  ports:
    - name: http
      port: 80
      targetPort: 8003
      protocol: TCP
