"""
NEXUS Platform — CAD File Router
==================================
Serves STEP and STL files generated by FreeCAD and Zoo.dev tools.
Includes GD&T tolerance annotations for manufacturing.

Endpoints:
  GET  /api/v1/cad/{session_id}/status       — JSON availability check
  GET  /api/v1/cad/{session_id}/design.step  — STEP file download (FreeCAD)
  GET  /api/v1/cad/{session_id}/design.stl   — STL file download (FreeCAD)
  GET  /api/v1/cad/{session_id}/tolerances   — GD&T tolerance specs (JSON)
  GET  /api/v1/cad/{session_id}/zoo_design.step — STEP file download (Zoo.dev)
  GET  /api/v1/cad/{session_id}/zoo_design.stl  — STL file download (Zoo.dev)
  POST /api/v1/cad/text-to-cad               — Generate CAD from text (Zoo.dev)
  GET  /api/v1/cad/credits                   — Check Zoo.dev API credits
  GET  /api/v1/cad/health                    — Check Zoo.dev API health
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/cad", tags=["cad"])

CAD_OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent / "cad_output"


def _session_dir(session_id: str) -> Path:
    return CAD_OUTPUT_DIR / session_id


@router.get("/{session_id}/status")
async def cad_status(session_id: str) -> JSONResponse:
    """Check whether CAD files exist for a session (FreeCAD and Zoo.dev)."""
    d = _session_dir(session_id)
    
    # FreeCAD files
    step = d / "design.step"
    stl  = d / "design.stl"
    
    # Zoo.dev files
    zoo_step = d / "zoo_design.step"
    zoo_stl  = d / "zoo_design.stl"
    zoo_gltf = d / "zoo_design.gltf"

    # Read domain from a small metadata file if present
    domain = None
    meta_path = d / "meta.txt"
    if meta_path.is_file():
        domain = meta_path.read_text(encoding="utf-8").strip()

    freecad_available = (step.is_file() and step.stat().st_size > 100) or \
                        (stl.is_file()  and stl.stat().st_size  > 100)
    zoo_available = (zoo_step.is_file() and zoo_step.stat().st_size > 100) or \
                    (zoo_stl.is_file()  and zoo_stl.stat().st_size  > 100)
    
    # Tolerance specs
    tol_file = d / "tolerances.json"
    has_tolerances = tol_file.is_file()
    tolerance_summary = None
    if has_tolerances:
        try:
            import json
            with open(tol_file, "r", encoding="utf-8") as f:
                tol_data = json.load(f)
            tolerance_summary = {
                "iso_class": tol_data.get("iso_tolerance_class"),
                "material": tol_data.get("material", {}).get("name"),
                "surface_finish_ra_um": tol_data.get("surface_finish_ra_um"),
                "num_annotations": len(tol_data.get("critical_dimensions", [])),
            }
        except Exception:
            pass

    return JSONResponse({
        "available":  freecad_available or zoo_available,
        "session_id": session_id,
        "domain":     domain,
        # FreeCAD files
        "freecad": {
            "has_step": step.is_file() and step.stat().st_size > 100,
            "has_stl":  stl.is_file()  and stl.stat().st_size  > 100,
            "step_size": step.stat().st_size if step.is_file() else 0,
            "stl_size":  stl.stat().st_size  if stl.is_file()  else 0,
        },
        # Zoo.dev files
        "zoo_dev": {
            "has_step": zoo_step.is_file() and zoo_step.stat().st_size > 100,
            "has_stl":  zoo_stl.is_file()  and zoo_stl.stat().st_size  > 100,
            "has_gltf": zoo_gltf.is_file() and zoo_gltf.stat().st_size > 100,
            "step_size": zoo_step.stat().st_size if zoo_step.is_file() else 0,
            "stl_size":  zoo_stl.stat().st_size  if zoo_stl.is_file()  else 0,
            "gltf_size": zoo_gltf.stat().st_size if zoo_gltf.is_file() else 0,
        },
        # GD&T tolerances
        "tolerances": {
            "available": has_tolerances,
            "summary": tolerance_summary,
        },
        # Legacy fields for backwards compatibility
        "has_step":   step.is_file() and step.stat().st_size > 100,
        "has_stl":    stl.is_file()  and stl.stat().st_size  > 100,
        "step_size":  step.stat().st_size if step.is_file() else 0,
        "stl_size":   stl.stat().st_size  if stl.is_file()  else 0,
    })


@router.get("/{session_id}/design.step")
async def download_step(session_id: str) -> FileResponse:
    """Download the STEP file for a session."""
    path = _session_dir(session_id) / "design.step"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="STEP file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="application/step",
        filename=f"nexus_{session_id[:8]}_design.step",
    )


@router.get("/{session_id}/design.stl")
async def download_stl(session_id: str) -> FileResponse:
    """Download the STL file for a session."""
    path = _session_dir(session_id) / "design.stl"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="STL file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="model/stl",
        filename=f"nexus_{session_id[:8]}_design.stl",
    )


@router.get("/{session_id}/tolerances")
async def download_tolerances(session_id: str) -> JSONResponse:
    """
    Download GD&T tolerance specifications for a session.
    
    Returns JSON with:
    - ISO tolerance class
    - Material specification
    - Critical dimensions with tolerances
    - Surface finish requirements
    - Manufacturing notes
    """
    path = _session_dir(session_id) / "tolerances.json"
    if not path.is_file():
        raise HTTPException(status_code=404, detail="Tolerance specs not available for this session")
    
    import json
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    
    return JSONResponse(data)


# ── Zoo.dev Text-to-CAD Endpoints ────────────────────────────────────────────

class TextToCADRequest(BaseModel):
    """Request model for Zoo.dev Text-to-CAD generation."""
    prompt: str = Field(..., min_length=10, max_length=2000, description="Natural language part description")
    session_id: str = Field(..., min_length=1, max_length=100, description="Session ID for file organization")
    output_formats: List[str] = Field(default=["step", "stl"], description="Output formats: step, stl, gltf")


class TextToCADResponse(BaseModel):
    """Response model for Zoo.dev Text-to-CAD generation."""
    success: bool
    step_path: Optional[str] = None
    stl_path: Optional[str] = None
    gltf_path: Optional[str] = None
    generation_time_seconds: float
    estimated_cost_usd: float
    error_message: Optional[str] = None


class CreditsResponse(BaseModel):
    """Response model for Zoo.dev API credits check."""
    available: bool
    free_minutes_remaining: Optional[float] = None
    error: Optional[str] = None


@router.post("/text-to-cad", response_model=TextToCADResponse)
async def generate_cad_from_text(request: TextToCADRequest):
    """
    Generate CAD files from natural language prompt using Zoo.dev API.
    
    Pricing: $0.50/minute, 20 free minutes/month included.
    
    Example prompt: "cylindrical heatsink, 50mm diameter, 30mm tall, with 12 radial fins"
    """
    try:
        from app.tools.zoo_cad_tool import get_zoo_client
    except ImportError as e:
        raise HTTPException(status_code=500, detail=f"Zoo.dev tool not available: {e}")
    
    client = get_zoo_client()
    
    if not client.is_available:
        raise HTTPException(
            status_code=503,
            detail="Zoo.dev API not configured. Set ZOO_API_KEY environment variable."
        )
    
    result = await client.generate(
        prompt=request.prompt,
        session_id=request.session_id,
        output_formats=request.output_formats
    )
    
    return TextToCADResponse(
        success=result.success,
        step_path=result.step_path,
        stl_path=result.stl_path,
        gltf_path=result.gltf_path,
        generation_time_seconds=result.generation_time_seconds,
        estimated_cost_usd=result.estimated_cost_usd,
        error_message=result.error_message
    )


@router.get("/credits", response_model=CreditsResponse)
async def check_zoo_credits():
    """Check remaining Zoo.dev API credits."""
    try:
        from app.tools.zoo_cad_tool import get_zoo_client
    except ImportError:
        return CreditsResponse(available=False, error="Zoo.dev tool not available")
    
    client = get_zoo_client()
    
    if not client.is_available:
        return CreditsResponse(available=False, error="API key not configured")
    
    credits_info = await client.check_credits()
    
    if "error" in credits_info:
        return CreditsResponse(available=False, error=credits_info["error"])
    
    return CreditsResponse(
        available=True,
        free_minutes_remaining=credits_info.get("free_minutes_remaining")
    )


@router.get("/health")
async def cad_health():
    """Check Zoo.dev API connectivity and FreeCAD availability."""
    zoo_available = False
    zoo_url = None
    freecad_available = False
    freecad_path = None
    
    try:
        from app.tools.zoo_cad_tool import get_zoo_client
        client = get_zoo_client()
        zoo_available = client.is_available
        zoo_url = client.base_url if zoo_available else None
    except ImportError:
        pass
    
    try:
        from app.tools.freecad_tool import _find_freecad_exe
        freecad_path = _find_freecad_exe()
        freecad_available = freecad_path is not None
    except ImportError:
        pass
    
    # Fallback: check if any CAD output exists (means FreeCAD worked before)
    if not freecad_available:
        try:
            cad_output = Path(__file__).resolve().parent.parent.parent / "cad_output"
            if cad_output.exists() and any(cad_output.glob("*/design.step")):
                freecad_available = True
                freecad_path = "detected_from_output"
        except Exception:
            pass
    
    return {
        "zoo_api_configured": zoo_available,
        "zoo_api_url": zoo_url,
        "freecad_available": freecad_available,
        "freecad_path": freecad_path,
        "engines": {
            "freecad": "available" if freecad_available else "not_found",
            "zoo_dev": "configured" if zoo_available else "api_key_missing"
        }
    }


# ── Zoo.dev File Downloads ───────────────────────────────────────────────────

@router.get("/{session_id}/zoo_design.step")
async def download_zoo_step(session_id: str) -> FileResponse:
    """Download the Zoo.dev-generated STEP file for a session."""
    path = _session_dir(session_id) / "zoo_design.step"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="Zoo.dev STEP file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="application/step",
        filename=f"nexus_{session_id[:8]}_zoo_design.step",
    )


@router.get("/{session_id}/zoo_design.stl")
async def download_zoo_stl(session_id: str) -> FileResponse:
    """Download the Zoo.dev-generated STL file for a session."""
    path = _session_dir(session_id) / "zoo_design.stl"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="Zoo.dev STL file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="model/stl",
        filename=f"nexus_{session_id[:8]}_zoo_design.stl",
    )


@router.get("/{session_id}/zoo_design.gltf")
async def download_zoo_gltf(session_id: str) -> FileResponse:
    """Download the Zoo.dev-generated glTF file for a session."""
    path = _session_dir(session_id) / "zoo_design.gltf"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="Zoo.dev glTF file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="model/gltf+json",
        filename=f"nexus_{session_id[:8]}_zoo_design.gltf",
    )
