"""
NEXUS Platform — CAD File Router
==================================
Serves STEP and STL files generated by the FreeCAD tool for each session.

Endpoints:
  GET /api/v1/cad/{session_id}/status      — JSON availability check
  GET /api/v1/cad/{session_id}/design.step — STEP file download
  GET /api/v1/cad/{session_id}/design.stl  — STL file download
"""
from __future__ import annotations

import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, JSONResponse

router = APIRouter(prefix="/cad", tags=["cad"])

CAD_OUTPUT_DIR = Path(__file__).resolve().parent.parent.parent / "cad_output"


def _session_dir(session_id: str) -> Path:
    return CAD_OUTPUT_DIR / session_id


@router.get("/{session_id}/status")
async def cad_status(session_id: str) -> JSONResponse:
    """Check whether CAD files exist for a session."""
    d = _session_dir(session_id)
    step = d / "design.step"
    stl  = d / "design.stl"

    # Read domain from a small metadata file if present
    domain = None
    meta_path = d / "meta.txt"
    if meta_path.is_file():
        domain = meta_path.read_text(encoding="utf-8").strip()

    available = (step.is_file() and step.stat().st_size > 100) or \
                (stl.is_file()  and stl.stat().st_size  > 100)

    return JSONResponse({
        "available":  available,
        "session_id": session_id,
        "domain":     domain,
        "has_step":   step.is_file() and step.stat().st_size > 100,
        "has_stl":    stl.is_file()  and stl.stat().st_size  > 100,
        "step_size":  step.stat().st_size if step.is_file() else 0,
        "stl_size":   stl.stat().st_size  if stl.is_file()  else 0,
    })


@router.get("/{session_id}/design.step")
async def download_step(session_id: str) -> FileResponse:
    """Download the STEP file for a session."""
    path = _session_dir(session_id) / "design.step"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="STEP file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="application/step",
        filename=f"nexus_{session_id[:8]}_design.step",
    )


@router.get("/{session_id}/design.stl")
async def download_stl(session_id: str) -> FileResponse:
    """Download the STL file for a session."""
    path = _session_dir(session_id) / "design.stl"
    if not path.is_file() or path.stat().st_size < 100:
        raise HTTPException(status_code=404, detail="STL file not available for this session")
    return FileResponse(
        path=str(path),
        media_type="model/stl",
        filename=f"nexus_{session_id[:8]}_design.stl",
    )
